#!/usr/bin/env bash
set -euo pipefail

LOCAL_ENV="local.env"
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"

if [[ ! -f "$LOCAL_ENV" ]]; then
    echo "Error: local.env not found. Run 'make configure-dx' first." >&2
    exit 1
fi

# shellcheck source=local.env
source "$LOCAL_ENV"

# ── Validate ───────────────────────────────────────────────────────────────────

if [[ -z "${DX_SEARCH_VERSION:-}" ]]; then
    echo "Error: DX_SEARCH_VERSION is not set in local.env." >&2
    exit 1
fi

HCL_REGISTRY="${HCL_REGISTRY:-hclcr.io}"
DX_NAMESPACE="${DX_NAMESPACE:-dxns}"
DX_SEARCH_RELEASE="${DX_SEARCH_RELEASE:-dx-search}"
DX_RELEASE="${DX_RELEASE:-dx}"
DX_VERSION="${DX_VERSION:-}"
EDITOR="${EDITOR:-vi}"

LOCAL_CHART="charts/search/${DX_SEARCH_VERSION}/hcl-dx-search"
REFERENCE="charts/search/${DX_SEARCH_VERSION}/search-values-reference.yaml"
SEARCH_VALUES="charts/search/${DX_SEARCH_VERSION}/search-values.yaml"
SEARCH_VALUES_LOCAL="charts/search/${DX_SEARCH_VERSION}/search-values-local.yaml"

# ── Step 1: OpenSearch kernel prerequisite (vm.max_map_count) ─────────────────

echo "==> Checking OpenSearch kernel prerequisite..."
bash "${SCRIPT_DIR}/configure-search-prereqs.sh"
echo ""

# ── Step 2: Ensure namespace exists ───────────────────────────────────────────

if kubectl get namespace "$DX_NAMESPACE" &>/dev/null; then
    echo "Namespace '${DX_NAMESPACE}' already exists."
else
    echo "Creating namespace '${DX_NAMESPACE}'..."
    kubectl create namespace "$DX_NAMESPACE"
fi

# ── Step 3: Ensure chart is pulled ────────────────────────────────────────────

if [[ ! -d "$LOCAL_CHART" ]]; then
    echo ""
    echo "==> Local chart not found. Pulling from registry..."
    bash "${SCRIPT_DIR}/pull-search-chart.sh"
fi

# ── Step 4: Ensure reference values exist ─────────────────────────────────────

if [[ ! -f "$REFERENCE" ]]; then
    echo ""
    echo "==> Reference values not found. Generating from local chart..."
    bash "${SCRIPT_DIR}/pull-search-values.sh"
fi

# ── Step 5: Create user values file from reference if not present ──────────────

if [[ ! -f "$SEARCH_VALUES" ]]; then
    cp "$REFERENCE" "$SEARCH_VALUES"
    echo "Created ${SEARCH_VALUES} from reference."
fi

# ── Step 6: Generate TLS certs and k8s secrets ────────────────────────────────

echo ""
echo "==> Generating OpenSearch TLS certificates and k8s secrets..."
bash "${SCRIPT_DIR}/create-search-certs.sh"

# ── Step 7: Write local overrides ─────────────────────────────────────────────

DX_REGISTRY_SECRET="${DX_REGISTRY_SECRET:-dx-harbor}"

echo ""
echo "==> Writing local overrides to ${SEARCH_VALUES_LOCAL}..."

cat > "$SEARCH_VALUES_LOCAL" <<EOF
# Auto-generated by install-search.sh — do not edit manually.
# Merged after search-values.yaml so these always take precedence.

# Image registry and pull secret for hclcr.io.
images:
  repository: "${HCL_REGISTRY}"
  imagePullSecrets:
    - name: "${DX_REGISTRY_SECRET}"

# k3d only provides the local-path StorageClass (ReadWriteOnce).
volumes:
  openSearchManager:
    data:
      storageClassName: "local-path"
  openSearchData:
    data:
      storageClassName: "local-path"

# Match the Helm release name used for the DX deployment in this namespace.
configuration:
  automatedSetup:
    dxDeploymentName: "${DX_RELEASE}"
EOF

echo "Local overrides written."

# ── Step 8: Open values in editor ─────────────────────────────────────────────

echo ""
echo "Opening ${SEARCH_VALUES} in ${EDITOR}."
echo "Add any chart-specific overrides (image pull secrets, resource limits, etc.)"
echo "then save and exit to continue."
echo ""
read -rp "Press Enter to open the editor (Ctrl+C to abort)..."
"${EDITOR}" "$SEARCH_VALUES"

# ── Step 9: Helm install or upgrade ───────────────────────────────────────────

if helm status "$DX_SEARCH_RELEASE" -n "$DX_NAMESPACE" &>/dev/null; then
    ACTION="Upgrading"
else
    ACTION="Installing"
fi

echo ""
echo "${ACTION} HCL DX Search v2..."
echo "  Release   : ${DX_SEARCH_RELEASE}"
echo "  Namespace : ${DX_NAMESPACE}"
echo "  Version   : ${DX_SEARCH_VERSION}"
echo "  Chart     : ${LOCAL_CHART}"
echo "  Values    : ${SEARCH_VALUES}"
echo "  Overrides : ${SEARCH_VALUES_LOCAL}"
echo ""

helm upgrade --install "$DX_SEARCH_RELEASE" "$LOCAL_CHART" \
    --namespace "$DX_NAMESPACE" \
    -f "$SEARCH_VALUES" \
    -f "$SEARCH_VALUES_LOCAL"

echo ""
echo "${ACTION} submitted. Pods are starting."
echo "  Monitor : k9s -n ${DX_NAMESPACE}"
echo "  Watch   : kubectl get pods -n ${DX_NAMESPACE} -w"

# ── Step 10: Wire Search into DX ──────────────────────────────────────────────

MIDDLEWARE_SVC="${DX_SEARCH_RELEASE}-search-middleware-query"

echo ""
echo "─────────────────────────────────────────────────────────────────────"
echo "  Post-install: wire Search into DX"
echo "─────────────────────────────────────────────────────────────────────"

if [[ -z "${DX_VERSION:-}" ]]; then
    echo "  DX_VERSION is not set in local.env — cannot auto-upgrade DX."
    echo "  Set DX_VERSION in local.env and re-run 'make install-search' to"
    echo "  generate the dx-search-values.yaml overlay and upgrade DX automatically."
    exit 0
fi

DX_VALUES="charts/dx/${DX_VERSION}/dx-values.yaml"
DX_SEARCH_VALUES="charts/dx/${DX_VERSION}/dx-search-values.yaml"
DX_LOCAL_CHART="charts/dx/${DX_VERSION}/hcl-dx-deployment"

# Write the DX search overlay — always regenerated so it stays in sync.
cat > "$DX_SEARCH_VALUES" <<EOF
# Auto-generated by install-search.sh — do not edit manually.
# Passed as an additional -f overlay when upgrading the DX Helm release.
# Re-generated on every 'make install-search' run.
# Deleted and DX re-upgraded by 'make uninstall-search' to restore defaults.

applications:
  # Remote Search (legacy) is mutually exclusive with Search v2.
  remoteSearch: false

networking:
  # Routes DX to the Search v2 query middleware service.
  searchMiddlewareService: "${MIDDLEWARE_SVC}"

configuration:
  # Enables the Search v2 middleware connection from DX Core.
  searchMiddleware:
    enabled: true
    host: "${MIDDLEWARE_SVC}"
    port: 3000
    ssl: false
    # Must match security.pushAdministration in the search chart values.
    pushAdminUser: "pushadmin"
    pushAdminPassword: "adminpush"
  core:
    # Activates the Search v2 UI and redirects search inputs to v2.
    search:
      uiV2Enabled: true
      inputRedirectVersion: "v2"
      wcmVersion: "v2"
EOF

echo "  Wrote ${DX_SEARCH_VALUES}"

if [[ ! -f "$DX_VALUES" ]]; then
    echo "  ${DX_VALUES} not found — skipping DX upgrade."
    echo "  Run 'make install-dx' once the file exists; the overlay will be picked up automatically."
    exit 0
fi

if [[ ! -d "$DX_LOCAL_CHART" ]]; then
    echo "  Local DX chart not found at ${DX_LOCAL_CHART} — skipping DX upgrade."
    echo "  Run 'make install-dx' after pulling the chart."
    exit 0
fi

bash "${SCRIPT_DIR}/patch-dx-chart.sh"
echo "  Upgrading DX release '${DX_RELEASE}'..."
helm upgrade --install "$DX_RELEASE" "$DX_LOCAL_CHART" \
    --namespace "$DX_NAMESPACE" \
    -f "$DX_VALUES" \
    -f "$DX_SEARCH_VALUES"

echo ""
echo "DX upgraded. Search v2 is now wired."
echo "  Monitor : k9s -n ${DX_NAMESPACE}"
