#!/usr/bin/env bash
set -euo pipefail

LOCAL_ENV="local.env"
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"

if [[ ! -f "$LOCAL_ENV" ]]; then
    echo "Error: local.env not found. Run 'make configure-dx' first." >&2
    exit 1
fi

# shellcheck source=local.env
source "$LOCAL_ENV"

# ── Validate ───────────────────────────────────────────────────────────────────

if [[ -z "${DX_SEARCH_VERSION:-}" ]]; then
    echo "Error: DX_SEARCH_VERSION is not set in local.env." >&2
    exit 1
fi

HCL_REGISTRY="${HCL_REGISTRY:-hclcr.io}"
DX_NAMESPACE="${DX_NAMESPACE:-dxns}"
DX_SEARCH_RELEASE="${DX_SEARCH_RELEASE:-dx-search}"
DX_RELEASE="${DX_RELEASE:-dx}"
DX_VERSION="${DX_VERSION:-}"
EDITOR="${EDITOR:-vi}"

LOCAL_CHART="charts/search/${DX_SEARCH_VERSION}/hcl-dx-search"
REFERENCE="charts/search/${DX_SEARCH_VERSION}/search-values-reference.yaml"
SEARCH_VALUES="charts/search/${DX_SEARCH_VERSION}/search-values.yaml"
SEARCH_VALUES_LOCAL="charts/search/${DX_SEARCH_VERSION}/search-values-local.yaml"

# ── Step 1: OpenSearch kernel prerequisite (vm.max_map_count) ─────────────────

echo "==> Checking OpenSearch kernel prerequisite..."
bash "${SCRIPT_DIR}/configure-search-prereqs.sh"
echo ""

# ── Step 2: Ensure namespace exists ───────────────────────────────────────────

if kubectl get namespace "$DX_NAMESPACE" &>/dev/null; then
    echo "Namespace '${DX_NAMESPACE}' already exists."
else
    echo "Creating namespace '${DX_NAMESPACE}'..."
    kubectl create namespace "$DX_NAMESPACE"
fi

# ── Step 3: Ensure chart is pulled ────────────────────────────────────────────

if [[ ! -d "$LOCAL_CHART" ]]; then
    echo ""
    echo "==> Local chart not found. Pulling from registry..."
    bash "${SCRIPT_DIR}/pull-search-chart.sh"
fi

# ── Step 4: Ensure reference values exist ─────────────────────────────────────

if [[ ! -f "$REFERENCE" ]]; then
    echo ""
    echo "==> Reference values not found. Generating from local chart..."
    bash "${SCRIPT_DIR}/pull-search-values.sh"
fi

# ── Step 5: Create user values file from reference if not present ──────────────

if [[ ! -f "$SEARCH_VALUES" ]]; then
    cp "$REFERENCE" "$SEARCH_VALUES"
    echo "Created ${SEARCH_VALUES} from reference."
fi

# ── Step 6: Generate TLS certs and k8s secrets ────────────────────────────────

echo ""
echo "==> Generating OpenSearch TLS certificates and k8s secrets..."
bash "${SCRIPT_DIR}/create-search-certs.sh"

# ── Step 7: Write local overrides ─────────────────────────────────────────────

DX_REGISTRY_SECRET="${DX_REGISTRY_SECRET:-dx-harbor}"

echo ""
echo "==> Writing local overrides to ${SEARCH_VALUES_LOCAL}..."

cat > "$SEARCH_VALUES_LOCAL" <<EOF
# Auto-generated by install-search.sh — do not edit manually.
# Merged after search-values.yaml so these always take precedence.

# Image registry and pull secret for hclcr.io.
images:
  repository: "${HCL_REGISTRY}"
  imagePullSecrets:
    - name: "${DX_REGISTRY_SECRET}"

# k3d only provides the local-path StorageClass (ReadWriteOnce).
volumes:
  openSearchManager:
    data:
      storageClassName: "local-path"
  openSearchData:
    data:
      storageClassName: "local-path"

# Match the Helm release name used for the DX deployment in this namespace.
configuration:
  automatedSetup:
    dxDeploymentName: "${DX_RELEASE}"
EOF

echo "Local overrides written."

# ── Step 8: Open values in editor ─────────────────────────────────────────────

echo ""
echo "Opening ${SEARCH_VALUES} in ${EDITOR}."
echo "Add any chart-specific overrides (image pull secrets, resource limits, etc.)"
echo "then save and exit to continue."
echo ""
read -rp "Press Enter to open the editor (Ctrl+C to abort)..."
"${EDITOR}" "$SEARCH_VALUES"

# ── Step 9: Helm install or upgrade ───────────────────────────────────────────

if helm status "$DX_SEARCH_RELEASE" -n "$DX_NAMESPACE" &>/dev/null; then
    ACTION="Upgrading"
else
    ACTION="Installing"
fi

echo ""
echo "${ACTION} HCL DX Search v2..."
echo "  Release   : ${DX_SEARCH_RELEASE}"
echo "  Namespace : ${DX_NAMESPACE}"
echo "  Version   : ${DX_SEARCH_VERSION}"
echo "  Chart     : ${LOCAL_CHART}"
echo "  Values    : ${SEARCH_VALUES}"
echo "  Overrides : ${SEARCH_VALUES_LOCAL}"
echo ""

helm upgrade --install "$DX_SEARCH_RELEASE" "$LOCAL_CHART" \
    --namespace "$DX_NAMESPACE" \
    -f "$SEARCH_VALUES" \
    -f "$SEARCH_VALUES_LOCAL"

echo ""
echo "${ACTION} submitted. Pods are starting."
echo "  Monitor : k9s -n ${DX_NAMESPACE}"
echo "  Watch   : kubectl get pods -n ${DX_NAMESPACE} -w"

# ── Step 10: Wire Search into DX ──────────────────────────────────────────────

MIDDLEWARE_SVC="${DX_SEARCH_RELEASE}-search-middleware-query"

if [[ -z "${DX_VERSION:-}" ]]; then
    echo ""
    echo "─────────────────────────────────────────────────────────────────────"
    echo "  Post-install: wire Search into DX"
    echo "─────────────────────────────────────────────────────────────────────"
    echo "  DX_VERSION is not set in local.env — skipping automatic DX upgrade."
    echo "  Add the following to your DX values file and run 'make install-dx':"
    echo ""
    echo "    networking:"
    echo "      searchMiddlewareService: \"${MIDDLEWARE_SVC}\""
    echo ""
    exit 0
fi

DX_VALUES="charts/dx/${DX_VERSION}/dx-values.yaml"

if [[ ! -f "$DX_VALUES" ]]; then
    echo ""
    echo "─────────────────────────────────────────────────────────────────────"
    echo "  Post-install: wire Search into DX"
    echo "─────────────────────────────────────────────────────────────────────"
    echo "  ${DX_VALUES} not found — skipping automatic DX upgrade."
    echo "  Add the following to your DX values file and run 'make install-dx':"
    echo ""
    echo "    networking:"
    echo "      searchMiddlewareService: \"${MIDDLEWARE_SVC}\""
    echo ""
    exit 0
fi

echo ""
echo "─────────────────────────────────────────────────────────────────────"
echo "  Post-install: wire Search into DX"
echo "─────────────────────────────────────────────────────────────────────"

# Inject or update networking.searchMiddlewareService in DX values.
if command -v yq &>/dev/null; then
    yq e ".networking.searchMiddlewareService = \"${MIDDLEWARE_SVC}\"" -i "$DX_VALUES"
    echo "  Updated ${DX_VALUES} with networking.searchMiddlewareService."
else
    # Fallback: append a YAML fragment if key is not already present.
    if ! grep -q "searchMiddlewareService" "$DX_VALUES"; then
        printf '\n# Added by install-search.sh\nnetworking:\n  searchMiddlewareService: "%s"\n' \
            "$MIDDLEWARE_SVC" >> "$DX_VALUES"
        echo "  Appended networking.searchMiddlewareService to ${DX_VALUES}."
    else
        echo "  searchMiddlewareService already present in ${DX_VALUES} — skipping."
    fi
fi

DX_LOCAL_CHART="charts/dx/${DX_VERSION}/hcl-dx-deployment"
DX_VALUES_USED="$DX_VALUES"

if [[ ! -d "$DX_LOCAL_CHART" ]]; then
    echo "  Local DX chart not found at ${DX_LOCAL_CHART} — skipping DX upgrade."
    echo "  Run 'make install-dx' manually after pulling the chart."
    exit 0
fi

echo "  Upgrading DX release '${DX_RELEASE}' to apply search wiring..."
helm upgrade --install "$DX_RELEASE" "$DX_LOCAL_CHART" \
    --namespace "$DX_NAMESPACE" \
    -f "$DX_VALUES_USED"

echo ""
echo "DX upgraded. Search middleware service is now wired."
echo "  Monitor : k9s -n ${DX_NAMESPACE}"
